packages:
  - apps/*
  - packages/*
catalog:
  "@eslint/js": "^9.30.1"
  "concurrently": "^8.2.2"
  "eslint": "^9.30.1"
  "tsc-alias": "^1.8.16"
  "typescript": "^5.8.3"
  "typescript-eslint": "^8.35.1"
  "globals": "^16.4.0"
  "vite": "^5.0.0"